// File generated by FlutterFire CLI.
// IMPORTANT: Replace this file by running:
//
//   flutterfire configure
//
// in your project root AFTER setting up your Firebase project.
// This will generate the real firebase_options.dart with your project's config.
//
// Until then, this placeholder prevents compilation errors.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.\n'
          'Run: flutterfire configure',
        );
    }
  }

  // -----------------------------------------------------------------------
  // PLACEHOLDER — Replace with values from flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsohU_D79VvAQkHyAzCcDk1kMFVAvmy14',
    appId: '1:882298088308:android:477e6a7f164bb95b275a21',
    messagingSenderId: '882298088308',
    projectId: 'builder-app-6e7e5',
    storageBucket: 'builder-app-6e7e5.firebasestorage.app',
  );

  // -----------------------------------------------------------------------

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVKEi-u6WL1WQ6ubFZRh3fsRV1fmZGAzc',
    appId: '1:882298088308:ios:be6e290c6601cc9e275a21',
    messagingSenderId: '882298088308',
    projectId: 'builder-app-6e7e5',
    storageBucket: 'builder-app-6e7e5.firebasestorage.app',
    iosBundleId: 'com.builderapp.builderApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFNInW3nCtiZPb7sBg2FlL_ZnMoWL-suA',
    appId: '1:882298088308:web:d09d1d4d6a34738e275a21',
    messagingSenderId: '882298088308',
    projectId: 'builder-app-6e7e5',
    authDomain: 'builder-app-6e7e5.firebaseapp.com',
    storageBucket: 'builder-app-6e7e5.firebasestorage.app',
    measurementId: 'G-E0FRPM4QDK',
  );

}